title: Welcome to Food Scoot
description: a delivery app for all commodities (groceries, meals, snacks, etc.) built for mobile and web with secure technologies.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day